from fixedint.base import FixedInt, MutableFixedInt

# ignore mypy complaining about mismatching signatures
class Int8(FixedInt, int): ...  # type: ignore[misc]
class Int16(FixedInt, int): ...  # type: ignore[misc]
class Int32(FixedInt, int): ...  # type: ignore[misc]
class Int64(FixedInt, int): ...  # type: ignore[misc]
class UInt8(FixedInt, int): ...  # type: ignore[misc]
class UInt16(FixedInt, int): ...  # type: ignore[misc]
class UInt32(FixedInt, int): ...  # type: ignore[misc]
class UInt64(FixedInt, int): ...  # type: ignore[misc]
class MutableInt8(MutableFixedInt): ...
class MutableInt16(MutableFixedInt): ...
class MutableInt32(MutableFixedInt): ...
class MutableInt64(MutableFixedInt): ...
class MutableUInt8(MutableFixedInt): ...
class MutableUInt16(MutableFixedInt): ...
class MutableUInt32(MutableFixedInt): ...
class MutableUInt64(MutableFixedInt): ...
